scheme: "Neptune"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "282C36" # Dark background
dhl: "383C46" # Dark highlight
dt2: "686C76" # Dark bg text secondary
dt1: "A8ACB6" # Dark bg text primary
lbg: "F0F1F8" # Light background
lhl: "E0E1E8" # Light highlight
lt2: "808188" # Light bg text secondary
lt1: "404148" # Light bg text primary
red: "A97552" # Red
ora: "C78956" # Orange
yel: "B9A552" # Yellow
gre: "48B788" # Green
cya: "55AFAF" # Cyan
blu: "3C8CBB" # Blue
vio: "7A7DCA" # Violet
mag: "C789A6" # Magenta
