scheme: "Nefelio"
author: "Protesilaos Stavrou (https://protesilaos.com)"
dbg: "282326" # Dark background
dhl: "383336" # Dark highlight
dt2: "686356" # Dark bg text secondary
dt1: "82a3a6" # Dark bg text primary
lbg: "eaeff2" # Light background
lhl: "dadfe2" # Light highlight
lt2: "7a8fa2" # Light bg text secondary
lt1: "5a6662" # Light bg text primary
red: "ba3d5a" # Red
ora: "ca6f5f" # Orange
yel: "ca9e5d" # Yellow
gre: "1cb57a" # Green
cya: "34b7bd" # Cyan
blu: "3f8eda" # Blue
vio: "956cda" # Violet
mag: "c34d95" # Magenta
