scheme: "Flowerbed"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "233949" # Dark background
dhl: "334959" # Dark highlight
dt2: "738999" # Dark bg text secondary
dt1: "A3B9C9" # Dark bg text primary
lbg: "ECF3F2" # Light background
lhl: "DCE3E2" # Light highlight
lt2: "8C9392" # Light bg text secondary
lt1: "5C6362" # Light bg text primary
red: "D86A87" # Red
ora: "D89A47" # Orange
yel: "CD9A8A" # Yellow
gre: "5CBC7D" # Green
cya: "1CABA1" # Cyan
blu: "4AA7D2" # Blue
vio: "7988CA" # Violet
mag: "BC74AF" # Magenta
