scheme: "Blau"
author: "Protesilaos Stavrou (http://www.protesilaos.com)"
dbg: "28282F" # Dark background
dhl: "38383F" # Dark highlight
dt2: "68686F" # Dark bg text secondary
dt1: "98989F" # Dark bg text primary
lbg: "DFDCDE" # Light background
lhl: "CFCCCE" # Light highlight
lt2: "7F7C7E" # Light bg text secondary
lt1: "4F4C4E" # Light bg text primary
red: "A43D56" # Red
ora: "BB651B" # Orange
yel: "BB8B11" # Yellow
gre: "3BA67A" # Green
cya: "2F95A5" # Cyan
blu: "2F7CB1" # Blue
vio: "5E6FB5" # Violet
mag: "A5657A" # Magenta
